services:
  backend:
    image: ghcr.io/devyhj99/whosbuying-backend:latest
    container_name: whosbuying-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    env_file:
      - .env
    networks:
      - global-net

  gateway:
    image: ghcr.io/devyhj99/whosbuying-gateway:latest
    container_name: whosbuying-gateway
    restart: always
    ports:
      - "${GATEWAY_PORT:-8081}:${GATEWAY_PORT:-8081}"
    env_file:
      - .env
    networks:
      - global-net

networks:
  global-net:
    external: true
